
# real data
dataset: CIFAR100
real_data_path: /root/DD-Ranking/NCFM_eval/dataset/
custom_val_trans: null

# synthetic data
ipc: 10
im_size: [32, 32]
nclass: 100
width: 1.0
# agent model
model_name: ConvNet-3
use_torchvision: false

# data augmentation
data_aug_func: "dsa"
aug_params:
  flip: 0.5
  rotate: 15.0
  saturation: 2.0
  brightness: 1.0
  contrast: 0.5
  scale: 1.2
  crop: 0.125
  cutout: 0.5
use_zca: false

custom_train_trans: null
custom_val_trans: null

# training specifics
optimizer: sgd
lr_scheduler: step
weight_decay: 0.0005
momentum: 0.9
num_eval: 5
num_epochs: 1000
syn_batch_size: 128
real_batch_size: 256
default_lr: 0.01
num_workers: 4
device: cuda
syn_lr: 0.01
teacher_model_epoch: 20
pretrained_models_flod: /root/NCFM/pretrained_models/cifar100/softlabel
soft_label_mode: "S"
soft_label_criterion: "sce"
temperature: 1.0
# save path
save_path: ./results/cifar100/ipc10/NCFM.csv
